#!/bin/bash
source ~/.bashark/bashark.sh

echo "${BOLD}${UNDERLINE}${POWDER_BLUE}Built in:${NORMAL}"
echo ""

color 191
echo "Colors: ${NORMAL}"
echo ""

echo "BLACK ${BLACK}BLACK REVERSE: ${REVERSE}BLACK${NORMAL}"
echo "RED ${RED}RED REVERSE: ${REVERSE}RED${NORMAL}"
echo "GREEN ${GREEN}GREEN REVERSE: ${REVERSE}GREEN${NORMAL}"
echo "YELLOW ${YELLOW}YELLOW REVERSE: ${REVERSE}YELLOW${NORMAL}"
echo "POWDER_BLUE ${POWDER_BLUE}POWDER_BLUE REVERSE: ${REVERSE}POWDER_BLUE${NORMAL}"
echo "MAGENTA ${MAGENTA}MAGENTA REVERSE: ${REVERSE}MAGENTA${NORMAL}"
echo "CYAN ${CYAN}CYAN REVERSE: ${REVERSE}CYAN${NORMAL}"
echo "WHITE ${WHITE}WHITE REVERSE: ${REVERSE}WHITE${NORMAL}"

echo "${BRIGHT}BRIGHT${NORMAL}"
echo "${NORMAL}NORMAL${NORMAL}"
echo "${BLINK}BLINK${NORMAL}"
echo "${REVERSE}REVERSE${NORMAL}"
echo "${UNDERLINE}UNDERLINE${NORMAL}"
echo "${END_UNDERLINE}END_UNDERLINE${NORMAL}"
echo "${STANDOUT}STANDOUT${NORMAL}"
echo "${END_STANDOUT}END_STANDOUT${NORMAL}"

echo "Sleeping with the cursor shown for 2 seconds"
sleep 2
echo "${HIDE_CURSOR}Hiding cursor for 2 seconds"
sleep 2
echo "${SHOW_CURSOR}"